### ISSUE TITLE
Playbooks for Datapipeline node types use default NiFi port

### ISSUE THREAD

**Issue by kmlTE** [RADON-SODALITE/hybrid-compute-profile#5]
# Current behavior
Ansible playbooks used in Datapipeline node types use default NiFi port (8080), e.g. in [configure operation for radon.nodes.datapipeline.destination.PubsS3Bucket](https://github.com/RADON-SODALITE/radon-particles/blob/master/nodetypes/radon.nodes.datapipeline.destination/PubsS3Bucket/files/configure/configure.yml#L40). This causes an issue e.g. if a NiFi instance is instantiated on another non-default port (e.g. 8989).
```
Nifi:
  type: radon.nodes.nifi.Nifi
  metadata:
    x: "556"
    y: "358"
    displayName: "Nifi"
  properties:
    port: 8989
    component_version: "1.11.4"
  requirements:
    - host:
        node: OpenStack
        relationship: con_HostedOn_0
        capability: host
```

# Expected behavior
The node types and playbooks that call NiFi REST API should use the port specified in the NiFi service template. For that  the node types and playbooks should be updated pointing to the correct port.
